export const settingMock = {
  total: 25,
  data: [
    {
      category: '原材料和生产制造',
      categoryNo: '1',
      keyword: '物流和运输'
    },
    {
      category: '物流和运输',
      categoryNo: '2',
      keyword: '禁运'
    },
    {
      category: '销售和市场',
      categoryNo: '3',
      keyword: '运营'
    }
  ]
}

export const categoryListMock = [
  {
    code: 1,
    name: '原材料和生产制造'
  },
  {
    code: 2,
    name: '物流和运输'
  },
  {
    code: 3,
    name: '销售和市场'
  },
  {
    code: 4,
    name: '消费者'
  }
]

export const analysisMock = {
  total: 25,
  data: [
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: '',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: '123123'
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    },
    {
      category: '原材料和生产制造',
      keyword: 'tiktok',
      nickname: '𝓯𝓻𝓮𝓪𝓴𝔂 𝕸𝖊𝖑 🦇🥩 #1 KORRA/PINKIE KISSER !!',
      screenName: 'RealNygmaThe3rd',
      tweetUrl: 'https://x.com/RealNygmaThe3rd/status/1822251164555252065',
      tweetId: '1822251164555252065',
      tweetCreatedAt: '2024-08-10 12:38:28',
      retweetFrom: 'https://juejin.cn/',
      chineseText: 'Tiktok 他妈的什么 https://t.co/vLeoeDXVEG',
      viewCount: '4',
      favoriteCount: '0',
      replyCount: '0',
      retweetCount: '0',
      mediaType: 'photo',
      location: 'A psychiatric hospital',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://pbs.twimg.com/media/GUnvxosWcAEc6kR.jpg',
      remark: ''
    }
  ]
}

export const focusUserListMock = {
  total: 17,
  data: [
    {
      nickName: 'わい',
      screenName: 'Znbke3anJ'
    },
    {
      nickName: 'わい',
      screenName: 'Znbke3anJ'
    }
  ]
}

export const focusListMock = {
  total: 40,
  data: [
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: 'https://h5.sinaimg.cn/upload/1005/526/2021/08/23/text.png',
      remark: '12312323132131232131231231231231231ow_JrainboW 我很好奇它尝起来是否像ow_JrainboW 我很好奇它尝起来是否像',
      replyTo: '1123'
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: 'https://vdept3.bdstatic.com/mda-qhijwtdweijuvn7p/360p/h264/1724076445978263213/mda-qhijwtdweijuvn7p.mp4?v_from_s=hkapp-haokan-nanjing&auth_key=1724476828-0-0-4d60a6692c3ef7a06295f14b9b7d579a&bcevod_channel=searchbox_feed&pd=1&cr=0&cd=0&pt=3&logid=1228102200&vid=12016678394177211248&klogid=1228102200&abtest=87345_1',
      coverImgUrls: '',
      remark: ''
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: '',
      remark: ''
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: '',
      remark: ''
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布我很好奇它尝起来是否像布丁我很好奇它尝起来是否像布丁我很好奇它尝起来是否像布丁我很好奇它尝起来是否像布丁我很好奇它尝起来是否像布丁我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: '',
      remark: ''
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: '',
      remark: ''
    },
    {
      nickname: 'わい',
      screenName: 'Znbke3anJ',
      tweetUrl: 'https://x.com/Znbke3anJ/status/1810632765198455057',
      tweetId: '1810632765198455057',
      tweetCreatedAt: '2024-07-09 11:11:05',
      retweetFrom: '',
      chineseText: '@yellow_JrainboW 我很好奇它尝起来是否像布丁🫣',
      viewCount: '64',
      favoriteCount: '0',
      replyCount: '1',
      retweetCount: '0',
      mediaType: 'text',
      location: '関東',
      verifiedType: '--',
      videoUrl: '',
      coverImgUrls: '',
      remark: ''
    },
  ]
}
