export const mockData = {
  total: 20,
  data: [
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 1,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 2,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 3,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 4,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 5,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 6,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 7,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 8,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 9,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 10,
    },
    {
      publishTime: '2024-07-04',
      publishAddress: '欧洲',
      title: '销售额',
      sensitiveContent: '新台币',
      originalLink: 'https://www.baidu.com/',
      seq: 11,
    }
  ]
}
